# Specify the version of docker-compose
version: "2" # It matches local version of our docker compose

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 8000:8000 # Mapped docker port 8000(left-side) to our local port 8000 (right-side)
      - 9229:9229 # Default debugger port
    volumes:
      - ./apps/backend:/app/apps/backend # Mount the local src folder with our docker src to quick keep track of changes.
      - /app/apps/backend/node_modules # Making sure only docker uses it own node modules and not shares with host machine.
    command: yarn start:docker
    depends_on: # This makes sure our postgres server is running before backened server
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 8000
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:6.2.5-alpine

  postgres:
    image: postgres:14-alpine # More optimized version of postgres
    ports:
      - 5432:5432 # To connect postgres locallly outside docker
    environment:
      POSTGRES_DB: webapp_dev # Change _dev to _prod to define a production database
      POSTGRES_HOST_AUTH_METHOD: trust
