services:
  # Formhub Backend public service
  - type: web
    name: fh-prod-backend1
    env: node
    plan: free
    repo: https://github.com/Sapkota00Basanta/Monorepo-Form-Collector.git
    buildFilter:
      paths:
        - apps/backend/**
    buildCommand: yarn && yarn build --filter=backend # Since,it's a monorepo.
    startCommand: cd apps/backend; yarn start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fh-prod-db1
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fh-prod-redis1
          property: connectionString

  # Formhub Frontend public static service
  - type: web
    name: fh-prod-frontend1
    env: static
    repo: https://github.com/Sapkota00Basanta/Monorepo-Form-Collector.git
    buildFilter:
      paths:
        - apps/frontend/**
    buildCommand: yarn && yarn build --filter=frontend
    staticPublishPath: ./apps/frontend/build
    routes: # Redirecting every dynamic route back to index html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: GRAPHQL_HOST
        fromService:
          name: fh-prod-backend1
          type: web
          property: host

  # Formhub Redis service
  - type: redis
    plan: free
    name: fh-prod-redis1
    ipAllowList: [] # only follow internal connection

# Formhub Database service
databases:
  - name: fh-prod-db1
    plan: free
    ipAllowList: [] # only follow internal connection

